import type { Metadata } from "next";
import { Outfit, Gabriela } from "next/font/google";
import { NextIntlClientProvider } from "next-intl";
import { getLocale, getMessages } from "next-intl/server";
import "./globals.css";
import Sidebar from "@/components/layout/Sidebar";
import MainLayout from "@/components/layout/MainLayout";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { SHOW_INITIATIVE_SIDEBAR } from "@/lib/layout/layoutConfig";

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-sans",
});

const gabriela = Gabriela({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-serif",
});

export const metadata: Metadata = {
  title: "RPV Tabletop",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script
            async
            crossOrigin="anonymous"
            src="https://tweakcn.com/live-preview.min.js"
          />
      </head>
      <body
        className={`${outfit.variable} ${gabriela.variable} antialiased min-h-screen bg-background text-foreground${SHOW_INITIATIVE_SIDEBAR ? " flex" : ""}`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {SHOW_INITIATIVE_SIDEBAR ? (
              <aside className="hidden md:flex w-xs lg:w-sm p-3 pt-2">
                <Sidebar />
              </aside>
            ) : null}

            <div
              className={
                SHOW_INITIATIVE_SIDEBAR
                  ? "flex-1 min-h-screen p-3 md:p-4"
                  : "min-h-screen p-3 md:p-4"
              }
            >
              <MainLayout>{children}</MainLayout>
            </div>
            <Toaster />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
